# Header
menu:
  Irina Ebert: http://www.irinaebert.com/
  #Archives: /archives

# Title on top left of menu. Leave empty to use main blog title
menu_title: Latin Refreshed

# URL of the Home page image
index_cover: /img/home-bg.jpg

# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname:
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/IrinaEbert
facebook_url: https://www.facebook.com/keisha.cakes.3
github_url: https://github.com/iebert1/latin_refreshed
youtube_url: https://www.youtube.com/channel/UCvXnkUDgxrvn9UXuLWY0krg
